[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
linkify = "GsMY2V7Mz1utVJw3V2f1c3PAPoraiiDZeqWnnSU5AXbi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
